# 版本3支持集群部署 版本2仅支持单机部署
version: '3'
#声明volumes
volumes:
  volume-mongodb: { }
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /mnt/e/docker/mnt/minio/data:/data
    command: server /data
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /mnt/e/docker/mnt/redis/data:/data
      - /mnt/e/docker/mnt/redis/config:/etc/redis
    #指定授权密码, 持久化数据
    command: redis-server --appendonly yes --requirepass "chry"
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      # 由于兼容问题无法直接挂载win目录到mongo, 只能创建一个volume后挂载
      #- volume-mongodb:/data/db
      - ./mongo:/docker-entrypoint-initdb.d/
    # 启动授权登录
    command: --auth
